FROM python:3.11.9

WORKDIR /afk_slackbot
COPY . /afk_slackbot

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements-dev.txt

CMD ["pytest", "--disable-warnings", "tests", "-vv"]
