FROM python:3.11.9-slim

WORKDIR /afk_slackbot
COPY . /afk_slackbot

RUN apt update && apt install -y git
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements-dev.txt

CMD ["pytest", "--disable-warnings", "tests", "-vv"]
